### PR TITLE
🗃	데이버베이스 관련 수정 : 게임 결과 게임ID -> UUID 변경하고 결과안에 총 수익 손실 int 아닌 BIGINT 변경

### PR DESCRIPTION
**Pull request by kimkganghyun**

### CODE REVIEW

**Review by parkswon1 — DISMISSED** [review]
LGTM!

**Review by hashi285 — DISMISSED** [review]
확인했습니당

**Review by minseoBae — APPROVED** [review]
확인했습니당

**Review by parkswon1 — APPROVED** [review]
LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!LGTM!!!!!!!!!!!!!!!!!!!!!!!!!!

**Pull request merged**
